version: '3.8'

services:
    web:
        build: .
        container_name: finance-web
        ports:
            - "8005:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            - DB_HOST=db
            - DB_DATABASE=finance
            - DB_USERNAME=farai
            - DB_PASSWORD=@Paradice1

    db:
        image: mysql:5.7
        container_name: finance-data
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: finance
            MYSQL_USER: farai
            MYSQL_PASSWORD: '@Paradice1'
        volumes:
            - db_data:/var/lib/mysql
            - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
        ports:
            - "3308:3306"

volumes:
    db_data:
